version: "3"
services:
  auth:
    image: auth
    container_name: "auth"
    restart: always  
    # env_file: .env  
    environment:
      # - ENV_FILE=.env   # 读配置文件代替环境变量
      # JWT
      - JWT_EXPIRE=3600
      - JWT_SECRET=sahjdjsgaudsiudhuywnnml

      - AUTH_REDIS_PWD=123456
      - AUTH_REDIS_POOL_SIZE=100
      - AUTH_REDIS_INDEX=1
      - AUTH_REDIS_HOST=redis:6379    # cluster host
    ports:
      - 5000:5000
    depends_on:
      - redis
  redis:
      image: redis:latest
      container_name: redis
      restart: always
      # env_file: .env
      command: redis-server --requirepass 123456
      ports:
        - 6379:6379